### ISSUE TITLE
Expose `maintainCase` to the user

### ISSUE THREAD

**Issue by mhkeller** [Flet/github-slugger#13]
In [index.js](https://github.com/Flet/github-slugger/blob/master/index.js#L53), there is a conditional to maintain the case but no way to pass that in. It would be great if this were exposed to the user.

I put together [an implementation on a fork](https://github.com/mhkeller/github-slugger/tree/maintainCase-support) including tests. I can PR if you're interested.

**Comment by Flet** [comment]
Nice! Sure, PR away! :)

**Comment by wooorm** [comment]
This was closed when GH-14 got merged!
