### ISSUE TITLE
Expose slugger function

### ISSUE THREAD

**Issue by bobylito** [Flet/github-slugger#28]
Thanks for this project. In a project of mine, I need the slug function, but the iteration gets in the way. I want to expose the [slugger function](https://github.com/Flet/github-slugger/blob/master/index.js#L46-L54) as a "static" method of the GithubSLugger object. This change would let us use the slugger directly, in this way:

```js
import GithubSlugger from 'GitHub-slugger'

GithubSlugger.slugger('my text to slug')
```

What do you think?

**Comment by bobylito** [comment]
If you like the idea, I'll open the PR right away. :D

**Comment by wooorm** [comment]
How would that work with conflicts?

**Comment by bobylito** [comment]
> How would that work with conflicts?

I'm not sure what you mean by conflicts :)

It's a new API, so I don't think it would conflict with anything else.

**Comment by bobylito** [comment]
> I'm not sure what you mean by conflicts :)

Do you mean what happens if there are multiple slugs with the same key and we want `-1` and `-2`? It wouldn't handle that. That's actually the point of this modification: being able to access the transformation to slug without the state and the conflict handling mechanism.

**Comment by wooorm** [comment]
Yup, that’s what I meant!

Why would you want to create slugs that could clash?

One problem with adding `GithubSlugger.slug` is that it would be unclear that one is stateless, whereas `slugger.slug` is stateful. Not sure if that’s big of a problem, but it could be hard to understand for users.

**Comment by bobylito** [comment]
Fair point!

I don't have the data about the typology of users here. I'm gonna make a hypothesis here: I think the users of this library are pretty low-level, and they expect the flexibility trade-off that leans towards a more complex API. I'm thinking tools creators that integrate this library in other library or plugins.

However, if you don't think it's the case, then it could be a hidden API that is there but not documented in the readme.

**Comment by bobylito** [comment]
> Why would you want to create slugs that could clash?

That's a good question; I think :) In my use case, I'm creating the URLs and the anchors in the same page. I guess I'm doing something "wrong" as I have the `-1` generated. Then if there were no conflict handling systems, I wouldn't have to understand the behavior of the library.

**Comment by wooorm** [comment]
Alright, I’m up for this, PR would be welcome! `slugger` as a name?
