### ISSUE TITLE
html tags should be removed

### ISSUE THREAD

**Issue by UziTech** [Flet/github-slugger#30]
Html tags should be removed entirely not just the brackets.

## example

`slugger.slug('header <em>html</em>')`

### expected

`header-html`

### actual

`header-emhtmlem`

**Comment by wooorm** [comment]
Markdown or HTML parsing is not in the scope of this project, `github-slugger` expects plain text values. I’ll add a note to the readme.

I’d recommend (`remark` +) `rehype` or (`marked` +) `jsdom` for this.
