### ISSUE TITLE
Accents/diacritics should be replaced

### ISSUE THREAD

**Issue by loque** [Flet/github-slugger#31]
Currently I have headings with accents that cause some trouble when linking from another page. For example:
```js
var GithubSlugger = require("github-slugger")
var slugger = new GithubSlugger()
console.log(slugger.slug('Ñacurutú'))
```
Prints `ñacurutú` and it should print `-acurut-`.

I could fix this, if you are interested.

**Comment by wooorm** [comment]
You say the actual output is `ñacurutú`, and your expected output is `-acurut-`.

GitHub seems to produce `actual`, not `expected`: https://gist.github.com/wooorm/05c114ae71e0aa5874b70f5c893fc822#ñacurutú.

Why should it be `-acurut-`?

**Comment by loque** [comment]
Oh you are totally right. I was checking with the transformation that github does when you try to create a new repo. Sorry about that!

**Comment by wooorm** [comment]
ahh, from what I know about parsing that, that’s very different algorithm (only allowing ascii), but I’m not entirely sure how it works, although it matches:

https://github.com/remarkjs/remark-github/blob/2e23f2f9e73b79cf037432edf892acd53aff1006/lib/index.js#L30
