### ISSUE TITLE
Foreign characters not converted properly

### ISSUE THREAD

**Issue by niftylettuce** [Flet/github-slugger#32]
e.g. `Comment démarrer et configurer le transfert d'e-mails` becomes `#comment-d%C3%A9marrer-et-configurer-le-transfert-de-mails`, which is an unrecognized expression

**Comment by wooorm** [comment]
Sounds a lot like https://github.com/remarkjs/remark-slug/issues/12, and other previously opened issues here.

That URL works on GitHub: https://gist.github.com/wooorm/13a6f9445642976dd42304d370addbd9#comment-d%C3%A9marrer-et-configurer-le-transfert-de-mails
