### ISSUE TITLE
Slug contains unwanted hyphen after number

### ISSUE THREAD

**Issue by PaulBunker** [Flet/github-slugger#33]
slugger.slug('3d scene')

returns '3-d-scene'

expected '3d-scene'

**Comment by wooorm** [comment]
You probably have some unicode character in there, because for:

```js
var slug = require("github-slugger").slug

slug('3d scene')
```

I get the expected value: `"3d-scene"` on [runkit](https://npm.runkit.com/github-slugger)

**Comment by PaulBunker** [comment]
Ah, ok I'll investigate further on my end. Thanks for the quick reply.
