### ISSUE TITLE
Support for german umlaute 

### ISSUE THREAD

**Issue by tonprince** [Flet/github-slugger#37]
German Umlaute characters like 'ö', 'ä', 'ü' should be converted into 'oe', 'ae' or 'ue' to have less problems with different browser support.

**Comment by wooorm** [comment]
This project follows GitHub, which does not change the diaeresis (those two dots) into other letters. You are free to implement your own slugging algorithm however you please, but it doesn’t make sense here

**Comment by Flet** [comment]
Closing, but feel free to comment.
