### ISSUE TITLE
1.4.0 cannot work as expected with Chinese punctuation

### ISSUE THREAD

**Issue by vagusX** [Flet/github-slugger#39]
```
var GithubSlugger = require('github-slugger')
var slugger = new GithubSlugger()

slugger.slug('你好，世界') // 你好世界
```

![image](https://user-images.githubusercontent.com/6828924/130718043-e21caab5-8f66-4d58-9a38-a9e85e900d75.png)

**Comment by wooorm** [comment]
So, this project follows github. Before we had some bugs, now those are fixed! This is exactly how github works. Try it out in a readme or in a gist
