### ISSUE TITLE
Slugger for Foliant CustomIDs

### ISSUE THREAD

**Issue by holamgadol** [Flet/github-slugger#41]
I want to make a parser for headings in Foliant projects with [CustomIDs](https://foliant-docs.github.io/docs/preprocessors/customids/).

For example `# Long heading {#shortref}` should result in two refs:
- `long-heading`
- `shortref`

Your projects has a basic functionality for this task. I tried to add a possibility to parse CustomdIDs, but it became incompatible with existing version because `slugger` function returns an array of strings now.

Do you need such functionality in this project or I just can continue my efforts in the fork?

**Comment by wooorm** [comment]
This project matches GitHub. There are many other projects that do custom slugging.
