### ISSUE TITLE
Postgres function

### ISSUE THREAD

**Issue by Djboy08** [Flet/github-slugger#45]
Is there anyway to mimic a postgres slugify function for this? I use this slugger on the front-end, but I also want my database to manually created the slugs for updated/inserted data. Ive been trying to make a working copy of this but every resource I have found online usually does not include multiple spaces as dashes and just trims it.

**Comment by wooorm** [comment]
Hi! Closing as this is more of a question, not something to be solved here :)

I dunno, I have no postgress experience.
If postgress functions are turing complete, sure, should be possible.
But it’s probably terrible difficult.

Anyway, you probably don’t need to. You can probably use a programming language, like JavaScript, on the server.
