### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by getellez** [Flet/github-slugger#49]
I'm working on a project with NextJS, Jest, and Typescript and my tests are not passing because 'github-slugger' is using ESM imports

![image](https://github.com/Flet/github-slugger/assets/85968117/09a10b28-10cd-4a07-bfa0-73b1f3b3812a)

is it possible to turn the package to use commonjs?

**Comment by wooorm** [comment]
Hey!

Use old versions if you want CJS.
Other users want ESM.
The tools you use support ESM.
See https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c and many other sources on the internet for how to use ESM.
