### ISSUE TITLE
Accented letters

### ISSUE THREAD

**Issue by rkyoku** [Flet/github-slugger#51]
Hi,

Accented letters do not seem to be converted to their "unaccented" counterpart: `Prétérit` gives `prétérit` instead of `preterit`.

I reckon something identical happens with the apostrophe: `L'aoriste` gives `laoriste` which is imperfect, `l-aoriste` would be better (for both readability and SEO purposes I guess), or worst case `aoriste` (dropping the `l` completely, if need be).

What do you think?

Best,

**Comment by wooorm** [comment]
> which is imperfect

No, I think its perfect.

This project does what GH does, there are many sluggers that you can choose to do all kinds of things. This one is the only one that does GH. And it's not going to do something else.

Also: it's a Unicode world. You can use emoji and accents etc fine.
